from .login_form import LoginForm
from .signup_form import SignUpForm
from .make_watchlist import WatchlistForm
from .watchlist_stocks import WatchlistStocksForm
from .stock_search import StocksSearchForm
from .buy_stock_form import BuyStockForm
from .sell_stock_form import SellStockForm
from .update_stock_form import UpdateStockForm
from .stock_symbols_form import TickerPricesForm
from .stock_historical_form import HistoricalDataForm
